### ISSUE TITLE
Support for built-in tagged elements (uuid and inst)

### ISSUE THREAD

**Issue by MrEbbinghaus** [replikativ/hitchhiker-tree#8]
`hitchhiker.tree.core/order-on-edn-types` does not support uuids or insts. 
This prevents uuids from being used in lookup refs in datahike.

**Comment by whilo** [comment]
This has been addressed in https://github.com/replikativ/hitchhiker-tree/pull/7 and will be part of the next datahike release.

**Comment by MrEbbinghaus** [comment]
Nice. 

Didn't check the PRs...
